# Site
name: "뚜벅이"
title: "뚜벅이"
description: "투쟁하는 노동자와 함께하는 부산경남 청소년 연대모임"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.svg'
baseurl: https://youthwithworker.netlify.app
google_analytics: 'G-5HV5S7RZ97'
include: ["_pages"]
permalink: /post/:year/:month/:day/:title/

# Authors
authors:
  twitter: youthwithworker
  facebook: youthwithworker
  instagram: youthwithworker
  email: eksrufxnwod1103@gmail.com

# Plugins
plugins:
  - jekyll-paginate-v2



pagination: 
  enabled: true
  paginate:
    path:       /news/page:num
    per_page:   6
  paginate:
    path:       /data/page:num
    per_page:   6
  paginate:
    path:       /actvism/page:num
    per_page:   6


# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
